all: init-code name-code banner_left-code time-code notes-code parameter_test-code mash-code processes-code less-code ls-code pong-code mv-code mkdir-code rm-code touch-code kill-code fork_bomb-code memory_bomb-code man-code

.PHONY init-code:
	$(MAKE) -C init

.PHONY name-code:
	$(MAKE) -C name

.PHONY banner_left-code:
	$(MAKE) -C banner_left

.PHONY time-code:
	$(MAKE) -C time

.PHONY notes-code:
	$(MAKE) -C notes

.PHONY parameter_test-code:
	$(MAKE) -C parameter_test

.PHONY mash-code:
	$(MAKE) -C mash

.PHONY processes-code:
	$(MAKE) -C processes

.PHONY less-code:
	$(MAKE) -C less

.PHONY ls-code:
	$(MAKE) -C ls

.PHONY pong-code:
	$(MAKE) -C pong

.PHONY mv-code:
	$(MAKE) -C mv

.PHONY mkdir-code:
	$(MAKE) -C mkdir

.PHONY touch-code:
	$(MAKE) -C touch

.PHONY rm-code:
	$(MAKE) -C rm

.PHONY kill-code:
	$(MAKE) -C kill

.PHONY fork_bomb-code:
	$(MAKE) -C fork_bomb

.PHONY memory_bomb-code:
	$(MAKE) -C memory_bomb

.PHONY man-code:
	$(MAKE) -C man