all: init-code name-code banner_left-code time-code estimate_uptime-code joeprogram-code joeprogram2-code joeprogram3-code notes-code parameter_test-code launcher-code processes-code less-code ls-code pong-code mv-code mkdir-code rm-code touch-code

.PHONY init-code:
	$(MAKE) -C init

.PHONY name-code:
	$(MAKE) -C name

.PHONY banner_left-code:
	$(MAKE) -C banner_left

.PHONY time-code:
	$(MAKE) -C time

.PHONY estimate_uptime-code:
	$(MAKE) -C estimate_uptime

.PHONY joeprogram-code:
	$(MAKE) -C joeprogram

.PHONY joeprogram2-code:
	$(MAKE) -C joeprogram2

.PHONY joeprogram3-code:
	$(MAKE) -C joeprogram3

.PHONY notes-code:
	$(MAKE) -C notes

.PHONY parameter_test-code:
	$(MAKE) -C parameter_test

.PHONY launcher-code:
	$(MAKE) -C launcher

.PHONY processes-code:
	$(MAKE) -C processes

.PHONY less-code:
	$(MAKE) -C less

.PHONY ls-code:
	$(MAKE) -C ls

.PHONY pong-code:
	$(MAKE) -C pong

.PHONY mv-code:
	$(MAKE) -C mv

.PHONY mkdir-code:
	$(MAKE) -C mkdir

.PHONY touch-code:
	$(MAKE) -C touch

.PHONY rm-code:
	$(MAKE) -C rm