all: banner_right.o
	~/Documents/OSProject/buildtools/local/bin/i686-elf-gcc -o banner_right banner_right.o ../../stdlib/stdlib.o -ffreestanding -nostdlib -std=gnu99

banner_right.o: banner_right.c
	~/Documents/OSProject/buildtools/local/bin/i686-elf-gcc -o banner_right.o -c banner_right.c -ffreestanding -nostdlib -std=gnu99