all: joeprogram4.o
	~/Documents/OSProject/buildtools/local/bin/i686-elf-gcc -o joeprogram4 joeprogram4.o ../../stdlib/stdlib.o -ffreestanding -nostdlib -std=gnu99

joeprogram4.o: joeprogram4.c
	~/Documents/OSProject/buildtools/local/bin/i686-elf-gcc -o joeprogram4.o -c joeprogram4.c -ffreestanding -nostdlib -std=gnu99