all: joeprogram3.o
	~/Documents/OSProject/buildtools/local/bin/i686-elf-gcc -o joeprogram3 joeprogram3.o ../../stdlib/stdlib.o -ffreestanding -nostdlib -std=gnu99

joeprogram3.o: joeprogram3.c
	~/Documents/OSProject/buildtools/local/bin/i686-elf-gcc -o joeprogram3.o -c joeprogram3.c -ffreestanding -nostdlib -std=gnu99